### ISSUE TITLE
Data v3

### ISSUE THREAD

**Issue by hal-shu-sato** [team-apm/apm-data#122]
I would like to formulate data v3 in response to hal-shu-sato/apm#387.

## Summary

- Use JSON and JSON Schema
- Support splitting data files
- Change to edit data from GUI implementing validation
- ID assignment

### Use JSON and JSON Schema

Refer to hal-shu-sato/apm#387

### Support splitting data files

These days, the apm-data packages file becomes bigger and bigger, so the data file becomes complicated.
To fix that, make a file like `sitemap.xml` so that maintainers can edit the database easier.

### Change to edit data from GUI implementing validation

Now, we edit the database manually but that is very tough and hard to maintain.
So I want to use GUI implementing validation such as apm-web.

### ID assignment

A unified ID would make it easier to transfer repositories.
It would be better if we issue only IDs.

### Niconi Commons ID

Refer to hal-shu-sato/apm#271

> AviUtl, plugins, and scripts are closely related to Niconico, and some of them require adding the ID to the contents tree.
I want to assist with that.
>
> Recently, a feature that allows adding IDs easily was released.
So using it is better.
https://blog.nicovideo.jp/niconews/159854.html

### To do

- [x] Convert to JSON and JSON Schema
- [x] Support splitting data files
- [x] GUI implementing validation
- [x] ID assignment
- [x] Niconi commons ID

**Comment by mitosagi** [comment]
For now I am considering extending `mod.xml` as follows.

```json
// mod.json

{
  "core": {
    "path": "core.json",
    "modified": "2021-12-27T22:23:00+09:00"
  },
  "convert": {
    "path": "convert.json",
    "modified": "2021-12-11T16:03:00+09:00"
  },
  "packages": [
    {
      "id": "apm/packagesMain",
      "path": "packages/main.json",
      "modified": "2022-02-18T05:48:00+09:00"
    },
    {
      "id": "apm/packagesAmate",
      "path": "packages/amate.json",
      "modified": "2022-02-18T05:48:00+09:00"
    }
  ],
  "scripts": [
    {
      "id": "apm/scriptsMain",
      "path": "scripts.json",
      "modified": "2021-12-27T22:23:00+09:00"
    }
  ]
}
```

**Comment by hal-shu-sato** [comment]
Yes. It's a good idea! Pretty much what I had in mind!😮
How do you think that the id is used?

**Comment by mitosagi** [comment]
Currently the `repository` in `apm.json` is the URL, but I would like to use this id instead. This will allow us to change the directory structure later and make debugging easier.

**Comment by hal-shu-sato** [comment]
I agree with the idea that we should reduce stored data.
I think that the `repository` makes it difficult for users to change their repository...
So, I suggested an ID assignment.
The system is that Team apm assigns a unique ID to plugins or scripts, and all repository maintainers use the ID.
It would maintain compatibility between repositories.

**Comment by mitosagi** [comment]
I now understand what ID assignment means. That's a good idea, I'll think about the specific way of id assignment.

**Comment by hal-shu-sato** [comment]
It may be none of my business, but I have to say it.
I have seen several projects where development has virtually stopped because of the loss of the maintainer.
I intend to keep this project going for the long term, but I don't know when I will no longer be able to develop it.
Also, it will be harder to develop apm than to fork apm-data.
That is why I made it possible to change the data repository at an early stage.
I would appreciate it if you would know the intent of this...

**Comment by hal-shu-sato** [comment]
I added about Niconi commons ID.

**Comment by mitosagi** [comment]
It will take time to implement a solid working packages.json GUI. How about releasing v3 without it?

**Comment by hal-shu-sato** [comment]
I agree with you.
Let's release apm first.

**Comment by hal-shu-sato** [comment]
I'm considering ending support for v2 soon.

**Comment by hal-shu-sato** [comment]
I'm considering ending support for v2 at the end of July.

**Comment by mitosagi** [comment]
I would say we have achieved all our goals considering the auto-sorting feature and the apm-web.
