### ISSUE TITLE
License Modification

### ISSUE THREAD

**Issue by mitosagi** [team-apm/apm-data#154]
## Is your feature request related to a problem? Please describe.

The next version of apm will import type declarations from apm-data repository. However, the license of this repository is more restrictive than the MIT license used by the apm repository.

## Describe the solution you'd like

Change the license of the files outside the folder named `data` to MIT in the next commit. To do this, it would require the consent of everyone (`@hal-shu-sato` , `@yumetodo` , and `@mitosagi` ) who has ever modified a file outside the `data` folder.

The `data` folder refers to the following at this time.
- `/data`
- `/v2/data`
- `/v3/data`

## Additional context

I look forward to your opinions.

**Comment by mitosagi** [comment]
[licensing - Declaring multiple licences in a GitHub project](https://softwareengineering.stackexchange.com/questions/304874/declaring-multiple-licences-in-a-github-project) is talking about dual licenses, not the multi-license we are considering, but it would be helpful.

How about creating `LICENSE.MIT.md` and `LICENSE.CC_BY-NC-SA_4.0.md` in the root folder and telling the scope of each in the README.md?

@yumetodo  Do you have any ideas?

**Comment by yumetodo** [comment]
1. What was the motivation to adopt CC BY-NC-SA, not CC BY-SA? 
2. Why don't you keep apm-data just as a data repository? I'd like to suggest you that cut-out type declarations into another repository which is licensed under less restriction than MIT License (something like CC0, or BSL-1.0, etc), then import it from apm and apm-data.

**Comment by mitosagi** [comment]
> 2. Why don't you keep apm-data just as a data repository? I'd like to suggest you that cut-out type declarations into another repository which is licensed under less restriction than MIT License (something like CC0, or BSL-1.0, etc), then import it from apm and apm-data.

I am in favor of splitting the repository. How about naming the new repository `apm-schema` and making it `CC BY 4.0` to ask for credit?

**Comment by hal-shu-sato** [comment]
> 1. What was the motivation to adopt CC BY-NC-SA, not CC BY-SA?

This is because plugins and scripts are provided free of charge and I do not think it is a good idea to profit from the data that is collected from this information.
I just want to prevent profit from being made in providing our data (e.g., a service where you can buy a fork of our data), and I think it is ok for software and others that use our data to profit from it.
I know that it is best to write a license including them by myself...

**Comment by yumetodo** [comment]
As one of the options, I'd like to suggest you put the profit problem into the principle of market competition.

Even though we drop `NC` and someone tries to sell apm-data, while we are keeping `BY-SA`, that will not work.

**Comment by hal-shu-sato** [comment]
Indeed, it is...
Seems unlikely that those who sell for a fee will benefit if we continue to update the data for free.

**Comment by mitosagi** [comment]
@hal-shu-sato Can I start creating an `apm-schema` repository?

**Comment by hal-shu-sato** [comment]
Yes.
Let's make it in the `team-apm` organization.
If you can't do that due to permission, please let me know.

**Comment by mitosagi** [comment]
It seems desirable to have a license change for apm-data. However, is it correct that it is not required?

**Comment by mitosagi** [comment]
Close the issue considering that a conclusion has been reached and that no TO DO has been set.
