### ISSUE TITLE
Data Addition Policy

### ISSUE THREAD

**Issue by mitosagi** [team-apm/apm-data#2]
## Style of  `packages.xml`
- Packages are sorted alphabetically by author name.
- Packages by the same author are sorted alphabetically by id.
- See Readme for other details.

### Plugin

| Author          | Progress | Update     |
| --------------- | -------- | ---------- |
| amate           | complete | 2021/08/30 |
| aoytsk          | complete | 2021/08/30 |
| AviUtl実験室    | complete | 2021/09/07 |
| karoterra       | complete | 2021/11/07  | 
| Maverick Tse    | complete | 2021/12/19 |
| oov             | complete | 2021/09/09 |
| rigaya          | complete | 2021/09/11 |
| rikky           | complete | 2021/12/18 |
| yu_noimage_     | complete | 2021/09/14 |
| しし/りっちゃん | complete | -          |
| ぽっぷん        | comlete  | -          |

### Script

| Author       | Progress | Update |
| ------------ | -------- | ------ |
| aodaruma | todo     |        |
| auls | todo     |        |
| goldenhige   | todo     |        |
| gometh       | WIP |  2022/01/30      |
| kaisatsu     | todo     |        |
| karoterra    | todo     |        |
| satsuki      | complete|     -   |
| tetu         | todo     |        |
| tim          | todo     |        |
| respectrum93 | todo     |        |
| rikky        | partial |        -|
| undofish     | partial |      -  |
| usagi        | todo     |        |

The list of authors may increase in the future.

**Comment by hal-shu-sato** [comment]
I may change it so that the type is determined programmatically as per #1, what do you think?

**Comment by mitosagi** [comment]
I think it should be changed too. I'm just adding the `<type>` because I don't want the XML to be unreadable until that PR is complete.

**Comment by hal-shu-sato** [comment]
Oh, I see.
Thank you for your consideration.

**Comment by hal-shu-sato** [comment]
Related to #3, I thought it would be a good idea to define a naming convention for IDs as well.
To be honest, the current naming of IDs is not good enough.
If we are going to change it, I think it should be in the pre-release.
Also, I am planning a breaking change in version control that will reset the installation information.

**Comment by mitosagi** [comment]
How about the following id naming convention?

Choose a file name from `<file>` that represents the plugin and use it as the id. If there is no representative name, use the name of the zip file. If there is a possibility of duplication, such as only one word, prefix the id with the author's name.

**Comment by hal-shu-sato** [comment]
Sure. That's a good idea.

**Comment by hal-shu-sato** [comment]
I came up with an idea to avoid conflicts by making the ID `author/package_name`.
I think it is also OK to use `@author/package_name` following npm specification.
It may be possible to support this in v2 or later, but I need a feature that converts `apm.json` to maintain compatibility.

**Comment by mitosagi** [comment]
Closed because the content is out of date.
