### ISSUE TITLE
feat: 目的に応じたプラグインを追加する機能

### ISSUE THREAD

**Issue by mitosagi** [team-apm/apm-data#246]
## 問題点

必要なプラグインを目的から探して一括でインストールできるようになれば便利です。

See also: https://github.com/team-apm/apm/issues/405

## 提案する解決方法

思いついたパッケージのセットを下に書いておきます。これらを依存パッケージ扱いでまとめてインストールできる新しいパッケージを作ることでプログラムの変更なしに機能を追加できます。

```
scrapbox.io/aviutl による推奨環境
L-SMASH Works MrOjii版 + InputPipePlugin + かんたんMP4出力 + patch.aul

AviUtl効率化 パッケージセット
シークバー＋ + 最終フレーム自動調整 + フィルタドラッグ移動 + エディットボックス最適化 + アイテム内音声波形 + LuaJIT

音声編集 パッケージセット
VSTホストプラグイン＋α + 少し音確認再生 + アイテム内音声波形
```

## 補足説明

対応するプルリクエスト
- https://github.com/team-apm/apm-data/pull/245

**Comment by hal-shu-sato** [comment]
いいアイデアですね。
filesをplaceholder.setのようにすれば、タイプ判定に使えるかもしれません。

**Comment by yumetodo** [comment]
package groupってことですか、依存パッケージとして必要なセットを指定すれば今のまま実現できたりしないですかね・・・

**Comment by hal-shu-sato** [comment]
一応、このIssueの説明と#245 を見ると、依存関係で実装しているみたいですね

**Comment by mitosagi** [comment]
AviUtlで動画を日常的に作っている人は実際にどんなプラグインを組み合わせて使っているか調べる必要がありそうです。

**Comment by hal-shu-sato** [comment]
そうですね。

あと、気になって今調べたら、`.set`が設定ファイルの拡張子に使われることがあるみたいです…
`.pkgset`くらい長くする方がよいかもしれないですね…
修正プッシュのあとにすみません……

**Comment by yumetodo** [comment]
導入するパッケージの一覧はdescriptionに書くんじゃなくて依存パッケージから生成できないものでしょうか

**Comment by hal-shu-sato** [comment]
確かにそうですね。
そこまでいくと、データ仕様を分割した方が良いような気もします。

**Comment by mitosagi** [comment]
依存するパッケージ一覧の表示機能は既存パッケージにもあっていいと思うので別PRとして送ろうと思います。
