### ISSUE TITLE
bug: システムロケールをUTF8にしているとaviutlが一部文字化けする

### ISSUE THREAD

**Issue by hinamimi** [team-apm/apm-data#439]
# 問題

Windows側の設定でシステムロケールをShift-JISではなく、UTF-8にしているとおすすめインストールの時点でAviutlの一部が文字化けする。

## 環境

- Windows11
- Aviutl: バージョン: 1.10 （最新版）
- 拡張編集: バージョン: 0.92 （最新版）

## 詳細

該当部分は以下の画像参照
![image](https://user-images.githubusercontent.com/68514104/209144299-05463f07-1481-4093-aebb-294b2db88686.png)

**Comment by mitosagi** [comment]
Issueの投稿ありがとうございます。

再現できました。

解凍されたプラグインファイルのハッシュ値は正常なので文字化けはAviUtl側で引き起こされていると思われます。apmの問題ではないためcloseします。
