### ISSUE TITLE
Make data entry easier

### ISSUE THREAD

**Issue by mitosagi** [team-apm/apm-data#89]
To make data entry easier, I have made the package maker that comes with apm available from your browser.
[You can try it from this link.](https://mitosagi.github.io/apm-web/)
Since this is still in the testing phase, I've set the data to be sent to issues in [my apm-data repository](https://github.com/mitosagi/apm-data/issues) to avoid cluttering up this repository.

Eventually, I plan to use this web app to automatically create PRs. At that time, data update will be done in the following way.
`apm-data --(jsDeliver)-> **package maker** --(Google Forms)-> issues --(CI)-> PRs --(review)-> apm-data`

Link to the repository: https://github.com/mitosagi/apm-web

**Comment by hal-shu-sato** [comment]
What a nice site!
It is very useful!

**Comment by mitosagi** [comment]
I will not implement automatic PR generation because it will eventually require human modifications.

Since the link to apm-web has been placed in apm, I will close this issue, considering that the announcement has been made.
